# Generated by Django 3.0 on 2023-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Some name', max_length=120)),
                ('highscore', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('email', models.CharField(default='Some email', max_length=120)),
            ],
        ),
    ]
