# Generated by Django 3.0 on 2023-04-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230421_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='Some name', max_length=120),
        ),
    ]
