# Generated by Django 3.0 on 2023-04-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_members_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='highscore',
            new_name='score',
        ),
    ]
